/**
 * Ambient type for the packed dictionary asset (WL-105), generated by
 * `scripts/generate-dictionary.py` and committed under
 * `src/assets/dictionary/`.
 *
 * Declared here rather than enabling `resolveJsonModule` so `tsc` never
 * parses the asset itself — it is ~1.7MB of packed records, and having the
 * compiler infer a literal type from it would cost real typecheck time for
 * no benefit. See `src/features/dictionary/dictionaryService.ts` for the
 * record encoding.
 */
declare module '@assets/dictionary/dictionary.pack.json' {
  const asset: {
    sourceName: string;
    sourceVersion: string;
    wordCount: number;
    /** Word-list size tiers; a record's flag byte indexes into this. */
    sizeTiers: number[];
    /** WL-106: count of allowed words per first letter, a-z. */
    replyCounts: number[];
    /** Newline-separated `word` + flag-character records, sorted ascending. */
    records: string;
  };
  export default asset;
}
